# Generated by Django 4.1.1 on 2023-01-24 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectricityMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Nazwa licznika", max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="MeterLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nazwa kontrahenta", max_length=250),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShareInMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cob_share", models.BooleanField(default=False)),
                ("cob_share_percent", models.FloatField(default=0)),
                ("museum_share", models.BooleanField(default=False)),
                ("museum_share_percent", models.FloatField(default=0)),
                ("pantheon_share", models.BooleanField(default=False)),
                ("pantheon_share_percent", models.FloatField(default=0)),
                ("institute_share", models.BooleanField(default=False)),
                ("institute_share_percent", models.FloatField(default=0)),
                ("outside_share", models.BooleanField(default=False)),
                ("outside_share_percent", models.FloatField(default=0)),
                (
                    "meter",
                    models.ForeignKey(
                        help_text="Nazwa licznika",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="energy.electricitymeter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeterConections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "master_meter",
                    models.ForeignKey(
                        help_text="Licznik nadrzędy",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nadlicznik",
                        to="energy.electricitymeter",
                    ),
                ),
                (
                    "sub_meter",
                    models.ForeignKey(
                        help_text="Licznik podrzędny",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="podlicznik",
                        to="energy.electricitymeter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="electricitymeter",
            name="meter_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="energy.meterlocation"
            ),
        ),
    ]
