# Generated by Django 4.1.1 on 2023-01-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaulValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MeterReadings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("meterreading", models.FloatField()),
                (
                    "meter",
                    models.ForeignKey(
                        help_text="Nazwa licznika",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="energy.electricitymeter",
                    ),
                ),
            ],
        ),
    ]
