# Generated by Django 4.1.1 on 2023-01-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0002_defaulvalues_meterreadings"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaulvalues", name="value", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="defaulvalues",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
