# Generated by Django 4.1.1 on 2023-01-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0003_defaulvalues_value_alter_defaulvalues_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meterconections",
            constraint=models.UniqueConstraint(
                fields=("sub_meter",), name="unique_sub_meter"
            ),
        ),
    ]
