# Generated by Django 4.1.1 on 2023-01-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0005_remove_meterconections_unique_sub_meter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meterreadings",
            name="costperkwh",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
