# Generated by Django 4.1.1 on 2023-01-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0006_meterreadings_costperkwh"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicesCostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(help_text="Rodzaj faktury", max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="InvoicesCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(help_text="Numer faktury", max_length=250),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_value", models.FloatField()),
                ("invoice_year_refers_to", models.IntegerField()),
                ("invoice_month_refers_to", models.IntegerField()),
                (
                    "invoice_type",
                    models.ForeignKey(
                        help_text="Rodzaj faktury",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="energy.invoicescosttype",
                    ),
                ),
            ],
        ),
    ]
