# Generated by Django 4.1.1 on 2023-01-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0007_invoicescosttype_invoicescost"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicesCostStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(help_text="Status faktury", max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="invoicescost",
            name="invoice_status",
            field=models.ForeignKey(
                default=0,
                help_text="Status faktury",
                on_delete=django.db.models.deletion.PROTECT,
                to="energy.invoicescoststatus",
            ),
            preserve_default=False,
        ),
    ]
