# Generated by Django 4.1.1 on 2023-01-30 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0008_invoicescoststatus_invoicescost_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="meterreadings",
            name="data_reading",
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoicescost",
            name="invoice_status",
            field=models.ForeignKey(
                help_text="Status faktury1",
                on_delete=django.db.models.deletion.PROTECT,
                to="energy.invoicescoststatus",
            ),
        ),
    ]
